name: Jest tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # install dependencies and run teest command
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      #  1. setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # 2. checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 3 install npm
      - name: Install dependencies
        run: npm install

      # 4 run tests
      - name: Run test command
        run: npm run test
